### ISSUE TITLE
All Pricing Should Be Formatted In Persian - ۹۰,۰۰۰ تومان

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#12]

**Comment by abedi-ir** [comment]
salam,
be nazar mirese baraye estefade az font IranSans license kharidary nakardeed !
bad az download akharin version az font IranSans, dar mohtavaye font pushe ba name 'Farsi_numerals' vojod darad ke ba replace kardan font hay in pushe ba font haye asli, adad hay site be sourat khodkar be sourat adad hay farsi neshan dade mishavand.
in pushe dar project shoma vojod nadarad.

**Comment by arya107** [comment]
salam, man etefaghan kharide boodam ino kheyli vaght pish, alan peyda mikonam Farsi_Numerals ro

**Comment by arya107** [comment]
man kole file ro baraye shoma send kardam, agar mitooni khodet upload koni chon manzooreto motevajeh nashodam ke chikar konam, merci
