### ISSUE TITLE
Upload Problems

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#176]
I tried uploading a .gif as a picture for a course and I received an error which is correct, but the page just continues to load. 

When I receive any error, the page should stop loading and allow me to correct my mistake instead of me rewriting all the data from the beginning after a hard refresh.

Also, in general when data inputted is incorrect in the form, the form should show the error and reset, instead of the loading bar showing continuously at the top of the page.

**Comment by abedi-ir** [comment]
Fixed by 1d21f097a925e0eb70791c845ec4d132107950d1
