### ISSUE TITLE
VIP Package Problems

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#177]
When a user clicks the dropdown button to select and buy the  1 year VIP package, they get sent to ZarinPal and the 1 month VIP package is selected, the user should be able to select one of the 3 different packages. 

Also on the dashboard’s Payment Table, the exact name of which VIP package purchased does not show, it just says VIP subscription, it should say for example something like 1 ماه عضویت ویژه.

**Comment by abedi-ir** [comment]
Fix in 8ab3dcaf5e7a13526bed084cc26afd5f5aabb4c4
