### ISSUE TITLE
Ticketing

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#185]
These 3 pages are for users:
/tickets
/singleticket
/createticket

This page is for admins:
/ticketoverview

**Comment by abedi-ir** [comment]
hi mojadad    
jenab doruodian dar ghesmate /ticketoverview baraye ticket'ha **LIKE** gozashid !    
mikhastam bedunam ke koja karbord darad ? va inke piadesazi beshe ya na ?

**Comment by abedi-ir** [comment]
btn ba icon check baraye che eghdami hast ?
![Screenshot from 2019-08-01 18-10-34](https://user-images.githubusercontent.com/29602827/62298270-f07fc200-b487-11e9-998e-c2779ec3e6af.png)

**Comment by arya107** [comment]
hi, hahahaha, like nist, masalan highlight mishe vase reminder, ticketha ke moheman mishe ba in dokme highlighteshon kard.

**Comment by arya107** [comment]
Button check masalan vase seen kardane, ke user bedone ke ticketesh seen shode. Agar joore dige benazaret behtare ino bezarim bego.

**Comment by arya107** [comment]
Salam, merci va khaste nabashid, kheyli khobe!

1 soal, agar user bekhad ye ticket besaze, dokmash to safheye `/tickets` nistesh, az koja mitone besaze?

**Comment by arya107** [comment]
Va emkanesh hast ke admin ba CKEditor message bezare? To `SingleTicket.vue` ye comment gozashte bodam, vali nemidonam agar shodani hastesh.

**Comment by arya107** [comment]
![Screenshot 2019-08-04 at 15 26 45](https://user-images.githubusercontent.com/28385499/62422745-8e63ce80-b6cc-11e9-8b90-17caffbe6509.png)

**Comment by arya107** [comment]
If possible on the `/ticketoverview` page, when the ticket ID is clicked, it should send user to the single ticket page.

**Comment by arya107** [comment]
Is it possible to remove the loading bar and spinner only on the single ticket page because its a little bit distracting?

**Comment by abedi-ir** [comment]
baraye harmored yek issue ijad shod.    
mavarad ra dar haman issue peygiri konid.

**Comment by arya107** [comment]
Merci mamnoonam
