### ISSUE TITLE
CKEditor Functions

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#193]
Please enable these options so I can use them in the editor:

- RTL Button (So user can switch text from RTL to LTR)

- Font Color Changer

- Custom Font Size

** Also, per our telephone discussion, please add all relevant functions to the CKEditor you think is useful for my site. Thanks

**Comment by abedi-ir** [comment]
this item not exists

- RTL Button (So user can switch text from RTL to LTR)

**Comment by arya107** [comment]
Hello, so what can we do?
