### ISSUE TITLE
Course Viewing For User

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#194]
In the single course page, when a unit is clicked in the سرفصل دوره section, it should not disappear when it is the unit being watched, but instead, the right side of the clicked unit should be highlighted.

**Comment by abedi-ir** [comment]
Fixed by 9f72be51f6ef71683134ca9daf58fe73ed6b011c

**Comment by arya107** [comment]
Hi,

When the unit is being watched, it still disappears from the سرفصل دوره section.
