### ISSUE TITLE
Mark Unit Complete

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#196]
The User can click the Mark Unit Complete button and a Tick icon is shown next to the unit name, and a progression bar on the page, as well as the course card, shows the % of how much they have viewed and completed the course.

![Mark Unit Complete Example](https://user-images.githubusercontent.com/28385499/61706690-f37b0400-ad5d-11e9-8fd6-bd29a4a2a104.png)

**Comment by arya107** [comment]
Also, the pie chart should only show if the user is enrolled onto the course.

**Comment by arya107** [comment]
Hello, 

On the website, I clicked complete on all the units for the Grammar Zaban Englisi course, and the total percentage is showing 85.71%. There are not any courses which I could click complete on.

If it's possible, can the button always show, and have to states, unit watched & unit not watched so the user can select between them if they need to restudy the unit?

Also if it is possible for a tick to show next to the unit name which is clicked complete so the user can see what they have done so far.

Thanks!

**Comment by arya107** [comment]
This course has 2 units, and the total is showing 400% when both units are selected as complete.

![Screenshot 2019-07-31 at 22 18 48](https://user-images.githubusercontent.com/28385499/62235041-3fbee780-b3e1-11e9-826f-844215529d4a.png)

**Comment by arya107** [comment]
Error on build:

 ERROR  Failed to compile with 1 errors                         12:48:55 PM

 error  in ./src/pages/SingleLesson/SingleLesson.vue?vue&type=script&lang=j
s&

Syntax Error: SyntaxError: /Users/arya/Documents/GitHub/AskArya-Node.js-Vue
.js/Client/src/pages/SingleLesson/SingleLesson.vue: Unexpected token (333:8
)

  331 |             this.loadingMarkAsDone = false;
  332 |           });
> 333 |       } else {
      |         ^
  334 |         this.canMarkAsDone = false;
  335 |         backend.get(`courses/${this.$route.params.slug}`).then(response => {
  336 |           this.course = response.data.data.course;


 @ ./src/pages/SingleLesson/SingleLesson.vue?vue&type=script&lang=js& 1:0-293 1:309-312 1:314-604 1:314-604
 @ ./src/pages/SingleLesson/SingleLesson.vue
 @ ./src/routes/routes.js
 @ ./src/routes/router.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://192.168.1.107:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by abedi-ir** [comment]
salam mojadad   
jenab doroudian aya file singleLesson ra taghir dadid?

**Comment by arya107** [comment]
Salam, 

Fekr nakonam, vali shayad dar hade html va css.

**Comment by abedi-ir** [comment]
lotfan barresi konid, line 333 file SingleLesson roye system shoma ba noskhe asli motafavet has   
https://github.com/arya107/AskArya-Node.js-Vue.js/blob/8c9754d0a6aa0ec7a965f00ee5f14a11eba8c29c/Client/src/pages/SingleLesson/SingleLesson.vue#L295   
emkan barresi as samt mn vojod nadarad.
ehtemalan yek `}` ezafi baste bashid

**Comment by arya107** [comment]
Man inaro 100% dast nazadam, line 333 vase man yechizi digas kolan.

**Comment by arya107** [comment]
Fekr konam dorost shodesh khod be khod

**Comment by arya107** [comment]
Thank you for adding the icons, its looking much better.

If possible can the icons be placed inside the blue button that says `رایگان`  `پرداختنی`  `VIP`, so basically the icon at default should show unit not complete until the user clicks it complete.
