### ISSUE TITLE
Build Process Errors

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#200]
Hi,
There are some errors during build on localhost as well as on the live server.

![Uploading Screenshot 2019-07-31 at 22.05.18.png…]()

**Comment by arya107** [comment]
![Screenshot 2019-07-31 at 22 05 18](https://user-images.githubusercontent.com/28385499/62234380-d4284a80-b3df-11e9-9640-f5ecabf85263.png)

**Comment by abedi-ir** [comment]
`no-console` would need to be set to 0 to disable it. See http://eslint.org/docs/rules/no-console.html

**Comment by arya107** [comment]
`'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off'`

Should I change the `off `to `0`?

**Comment by abedi-ir** [comment]
mitonid shart `process.env.NODE_ENV === 'production'` ra pak konid ta zamane build be sourate develop ham khata nadahad

**Comment by arya107** [comment]
Chashm mercii
