### ISSUE TITLE
Course Price Buy Button Not Showing

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#202]
Hi,

On the Course Page, the pricing button does not show so a user can click and buy the course.

https://www.askarya.ir/courses/%DA%AF%D8%B1%D8%A7%D9%85%D8%B1-%D8%B2%D8%A8%D8%A7%D9%86-%D8%A7%D9%86%DA%AF%D9%84%DB%8C%D8%B3%DB%8C

**Comment by abedi-ir** [comment]
salam    
inmored dar ghalebetoon naboude ast

**Comment by abedi-ir** [comment]
Fixed by 2d21386e611275407ac4b8337aae0b43398e9b41   :face_with_head_bandage:
