### ISSUE TITLE
CKEditor for admin in tickets

### ISSUE THREAD

**Issue by abedi-ir** [arya107/AskArya-Node.js-Vue.js#208]
Va emkanesh hast ke admin ba CKEditor message bezare? To `SingleTicket.vue` ye comment gozashte bodam, vali nemidonam agar shodani hastesh.

_Originally posted by @arya107 in https://github.com/arya107/AskArya-Node.js-Vue.js/issues/185#issuecomment-517993335_

**Comment by abedi-ir** [comment]
salam    
jenab doroudian emkan pazir hast vali inke ba tavajoh be sabeghe'ea ke dar morede ticket ha daram, ta behal be in chenin emkanati niaz nadashte'am.    
mayel hastid ta dar sahafat SingleTicket, CreateTicket dar sourati ke admin bashad va ticketoverview CKEditor bashad ?

**Comment by arya107** [comment]
Salam, mercii agar baraye admin bashe ke kheyli khoob mishe merci.
