### ISSUE TITLE
Registration Problem

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#215]
After user signs up, and clicks on activation email link, they are redirected to a 404 error page.

**Comment by abedi-ir** [comment]
سلام    
مشکل مذکور بررسی و مشکلی که فرمودید مشاهده نشد.    

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/29602827/64159458-8aec7000-ce4f-11e9-94e3-1ee215468d49.gif)

**Comment by abedi-ir** [comment]
مشکل بر روی سرورتون بررسی و پیدا شد.    
مشکل برطرف شد.
