### ISSUE TITLE
Ticket message problems

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#216]
After a ticket is sent, after a few seconds it is deleted. Please check the video.

**Comment by abedi-ir** [comment]
فیلمی که فرمودید کجا ارسال کردید؟    
لطف میکنید مراحل تولید مشکل را بفرمایید.    
چون من الان یک تیکت در سرورتون ایجاد کردم و تیکت و پیام های آن بدون مشکل به قوت خود باقی هستند

**Comment by arya107** [comment]
![59AEB15A-0B69-4D27-90BF-8032AC00B340](https://user-images.githubusercontent.com/28385499/64171595-48835d00-ce68-11e9-9c46-04f5bb723dfb.gif)

**Comment by abedi-ir** [comment]
با دسترسی مدیر در تیکتتون پیامی ارسال کردم و مشکل رو متاسفانه هنوز ندیدیم.    
https://askarya.ir/tickets/view/5d46c9ff17838b05447806b2

**Comment by arya107** [comment]
[Ticketing Problems.zip](https://github.com/arya107/AskArya-Node.js-Vue.js/files/3569570/Ticketing.Problems.zip)

**Comment by abedi-ir** [comment]
سلام مجدد    
جناب درودیان برای بررسی بیشتر کلمه عبور اکانتتون در سایت را تغییر و با اکانت شما وارد شدم.    
به نظر میرسه این مشکل فقط برای شما و بر روی سیستم شما هست. لطف کنید کش ها مربوط به وبسایتتون رو پاک و مجدد امتحان کنید.

**Comment by abedi-ir** [comment]
سلام    
لطف کنید مجددا روی نسخه ی نصب شده روی سرورتون امتحان کنید و نتیجه را گزارش کنید.

**Comment by arya107** [comment]
Yes, it is working now, thanks!
