### ISSUE TITLE
401 Error for Course page

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#234]
If a user is not signed in and visits a course: 

`http://localhost:8080/courses/%D8%AF%D9%88%D8%B1%D9%87-%D8%AC%D8%A7%D9%85%D8%B9-%D8%B5%D9%81%D8%B1-%D8%AA%D8%A7-%DB%B1%DB%B0%DB%B0-%DA%AF%D8%B1%D8%A7%D9%85%D8%B1`  

they get an error in the console `GET http://localhost:8080/api/v1/ net::ERR_ABORTED 401 (Unauthorized)`

**Comment by arya107** [comment]
Then if the user clicks an episode they get another error:

`GET http://localhost:8080/api/v1//courses/episode/download/5cd525128fcbbc29064cacb3?mac=5cf54d2b0c37e2620b6d8b6462fde720&t=1576706790561 net::ERR_ABORTED 404 (Not Found)`

**Comment by arya107** [comment]
![Screenshot (261)](https://user-images.githubusercontent.com/28385499/71076880-ae87bc00-219b-11ea-80cb-9bd9faca6e67.png)

**Comment by abbasmdev** [comment]
if use not login an check this page or most likely any of course pages will get 401

login users will not get this error.

this potentially can not be issue
