### ISSUE TITLE
Sign In BUG

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#236]
User cannot sign in with Google.

When they sign in with Email and Password, no data shows on their Dashboard
![Screenshot (273)](https://user-images.githubusercontent.com/28385499/71162785-148a4700-2261-11ea-81b4-0a8b0ba79cf7.png)
.

But when Backend is restarted, their data shows on their Dashboard.

**Comment by abbasmdev** [comment]
Cookies less expire time caused this issue
I changed expire time to browsers end time
so util user not closes browser every thing related to this issue most likely should work.
