### ISSUE TITLE
Edit Course

### ISSUE THREAD

**Issue by yeganemehr** [arya107/AskArya-Node.js-Vue.js#25]

**Comment by arya107** [comment]
When I tried to edit a course, I recieved this error:

لطفا اشتباهات زیر را تصحیح کنید:
درخواست شما زیاد بوده لطفا 15 دقیقه دیگر دوباره تلاش کنید

**Comment by abedi-ir** [comment]
in mored marbot be limit tedad darkhastha hast va be edit course marbot nist.
baraye hazf in limit lotf konin yek issuse jadid besazid.
