### ISSUE TITLE
User avatars

### ISSUE THREAD

**Issue by yeganemehr** [arya107/AskArya-Node.js-Vue.js#3]
Hi,
There is an avatar in each [course card](https://github.com/arya107/AskArya-Node.js-Vue.js/blob/master/Client/src/pages/FrontendPages/Components/TopCourses/Course.vue) but there isn't in [User model](https://github.com/arya107/AskArya-Node.js-Vue.js/blob/master/Server/app/models/user.js); So where avatars should save or load?

**Comment by abedi-ir** [comment]
salam,
moshkeli az babat tasvir profile bad az loggin mojadad moshahede nashod.
lotfan marahel reproduce moshkel ro dobare test konin va marahel ro dar sourat vojod moshkel tozih dahid.
