### ISSUE TITLE
Use Vue Bootstrap

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#38]
Use Vue Bootstrap to show the courses on the homepage as a Carousel 

https://bootstrap-vue.js.org/docs/components/carousel

**Comment by yeganemehr** [comment]
It's matter of extra-feature of frontend and isn't in our agreement.
You can do it yourself or we can discuss about it (among some other issues).

**Comment by arya107** [comment]
ok
