### ISSUE TITLE
Backend Google Sign In ERROR

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#57]
http://localhost:3000/auth/login

```
400. That’s an error.

Error: invalid_request

Missing required parameter: redirect_uri

Learn more

Request Details
response_type=code
scope=profile email
client_id=844333766248-n9t5cht6ug871b959t657cajk9sgclhn.apps.googleusercontent.com
That’s all we know.
```

**Comment by arya107** [comment]
Salam, man aslan nemitoonam sign in besham ke roo site kar konam bekhatere in bug.

**Comment by abedi-ir** [comment]
Go to the console of your project and look under API Access. You should see your client ID & client secret there, along with a list of redirect URIs. If the 'http://localhost:8080/auth/google/callback' URI  doesn't listed, click edit settings and add the URI to the list.
