### ISSUE TITLE
Courses & Blog Posts on mobile devices should be on a Carousel for easier viewing

### ISSUE THREAD

**Issue by arya107** [arya107/AskArya-Node.js-Vue.js#75]
something like this,

- https://github.com/SSENSE/vue-carousel
- https://bootstrap-vue.js.org/docs/components/carousel

**Comment by arya107** [comment]
```
        <el-carousel :interval="5000" arrow="always">
            <el-carousel-item v-for="course in topCourses" v-bind:key="course.id">
              <Course v-bind="course"></Course>
            </el-carousel-item>
          </el-carousel>
```

https://element.eleme.io/#/en-US/component/carousel

**Comment by abedi-ir** [comment]
jenab doroudian in carousel baraye tasavir ya div haye tamam safhe behinesazi shode va baraye morede shoma monaseb nist.    
agar baz ham mayel hastin ta khodetun ham natije ra bebinin, befarma'ean ta code sahih ro ersal konam.

**Comment by arya107** [comment]
Salam, 

Yani ba `Card mode` ke to site _https://element.eleme.io/#/en-US/component/carousel_ hast hame nemishe?

**Comment by abedi-ir** [comment]
kheyli bold va na'motagharen mishe va baraye mobile keyli koochic   
![Screenshot from 2019-08-05 16-53-35](https://user-images.githubusercontent.com/29602827/62464378-a9ecd900-b7a1-11e9-8c20-d5b2cab51af4.png)

**Comment by arya107** [comment]
Emkanesh hast bekhatere in code hast?

```
.top-courses-section {
    padding: 0 11%;
  }
```

**Comment by abedi-ir** [comment]
behtar shod
![Screenshot from 2019-08-05 16-58-06](https://user-images.githubusercontent.com/29602827/62464598-4c0cc100-b7a2-11e9-9b8a-7d47a8f710bf.png)

**Comment by arya107** [comment]
:D Emkanesh hast push konid?

**Comment by abedi-ir** [comment]
ro noskhe descktop keyli beham rikhte va amalan useless hast vali chon farmodin push mikonam

**Comment by arya107** [comment]
Merci, khodam yekarish mikonam faghat ro mobile intori display beshe.
